import { NextAuthProvider } from '@/providers/nextAuthProvider';
import { ToastProvider } from '@/components/ui/toasts/toastManager';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Centro de Control de Tickets",
  description: "Generated by RedSysControl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
